spring:
  application:
    name: CONFIG-DEFAULT

# eureka config
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default_Zone: http://localhost:8761/eureka
